---
# tasks file for nginx
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: true
  
- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present
  become: true

- name: Start and enable nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  become: true
